### ISSUE TITLE
Test transfer

### ISSUE THREAD

**Issue by gaurav1780** [gaurav1780/codingbat_python_project#2]
Ok, while I was recording the video for you all, I realized that adding test cases will be a giant pain in the backside unless they can be populated from my [gaurav.gupta@mq.edu.au](mailto:gaurav.gupta@mq.edu.au) account. However, I cannot give out that password to everyone.

The tests have been written with a purpose and not all tests are shown for the end-user in the output table.

So, the FIRST step has to be - one volunteer - who is willing to extract all test cases from my page, and populate them in an organized way (in an excel file or something) on github that others will use. 

Please do not change any of the existing questions (or anything else on [gaurav.gupta@mq.edu.au](mailto:gaurav.gupta@mq.edu.au) account on codingbat.com)

There are 161 problems, and assuming 2 minutes per problem, that is 5 hours of work. I can have a 10-minute meeting with whoever volunteers for this.

Please reply as a comment if you are happy to help in this first step, and I will assign this issue to you.

**Comment by leviofliccat** [comment]
Hey, I’m happy to do that if I haven’t been assigned a task yet.

**Comment by gaurav1780** [comment]
Yes, please. I will send you the password through email (Cyber people, don't judge me).
